# This is a basic workflow to help you get started with Actions
name: Attendance Record

# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
    #MI
    - cron: "15 14 * * 5"
    #CTC
    - cron: "15 16 * * 5"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Install requirements
        run: pip3 install -r requirements.txt
  
      - name: Mark Attendance
        env:
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          URL: ${{ secrets.URL }}
        run: python3 main.py
