# This is a basic workflow to help you get started with Actions
name: Attendance Record

# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
    #SBC
    - cron: "0 9 * * 1"
    #SBC
    - cron: "0 11 * * 1"
    #GP
    - cron: "0 14 * * 1"
    #CM
    - cron: "0 16 * * 2"
    #CM
    - cron: "0 11 * * 3"
    #GP
    - cron: "0 18 * * 4"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Install requirements
        run: pip3 install -r requirements.txt
  
      - name: Mark Attendance
        env:
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          URL: ${{ secrets.URL }}
        run: python3 main.py
